### ISSUE TITLE
External Cancellation Support

### ISSUE THREAD

**Issue by nealruggles1** [AndreasAmMueller/Modbus#13]
First off, thank you for putting this package together! It is very easy to interface with and a breeze to implement in my codebase.

I was wondering, is there any chance you can include external cancellation support? I'd like to optionally be able to pass in a CancellationToken and Cancel the operation.

As of now I just have to wait for the command and response (or timeout) then I can move on.

**Comment by AndreasAmMueller** [comment]
done with commit a6d1108 - closing

NuGet update follows soon.
