### ISSUE TITLE
TCP keepalive

### ISSUE THREAD

**Issue by taai** [AndreasAmMueller/Modbus#17]
Please, add support for TCP keepalive for TCP connections. Currently, if you disconnect the internet cable, this package does not react at all.

Here is an example code I use for TCP connections for them to react on disconnects. Probably should add an option to customize the time parameters...

```CSharp
var socket = tcpClient.Client;
socket.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.KeepAlive, true);
socket.SetSocketOption(SocketOptionLevel.Tcp, SocketOptionName.TcpKeepAliveTime, 5);
socket.SetSocketOption(SocketOptionLevel.Tcp, SocketOptionName.TcpKeepAliveInterval, 1);
socket.SetSocketOption(SocketOptionLevel.Tcp, SocketOptionName.TcpKeepAliveRetryCount, 3);
```

**=== UPDATE ===**

Turns out that these commands are not available on .NET Standard 2.0, so you need to set the values the old way:

```CSharp
uint keepAliveTime = 5000;
uint keepAliveInterval = 1000;

var keepAliveConfig = new byte[12];

// Turn keepalive on
BitConverter.GetBytes((uint)1).CopyTo(keepAliveConfig, 0);
// Set amount of time without activity before sending a keepalive
BitConverter.GetBytes((uint)keepAliveTime).CopyTo(keepAliveConfig, 4);
// Set keepalive interval
BitConverter.GetBytes((uint)keepAliveInterval).CopyTo(keepAliveConfig, 8);

// Set the keep-alive settings on the underlying Socket
tcpClient.Client.IOControl(IOControlCode.KeepAliveValues, keepAliveConfig, null);

// Always send packets immediately
tcpClient.Client.NoDelay = true;
```

By the way, the byte packing can be micro-optimized, if you want to...
```CSharp
var keepAliveConfig = new byte[] {
    1,
    0,
    0,
    0,
    (byte)keepAliveTime,
    (byte)(keepAliveTime >> 8),
    (byte)(keepAliveTime >> 16),
    (byte)(keepAliveTime >> 24),
    (byte)keepAliveInterval,
    (byte)(keepAliveInterval >> 8),
    (byte)(keepAliveInterval >> 16),
    (byte)(keepAliveInterval >> 24),
};
```

**Comment by AndreasAmMueller** [comment]
I'vre read a lot about that topic and faced the fact, that this will be a **windows-only** implementation as long as certain issues are open on Microsoft's side.

References:
- Ran into the same exception: https://github.com/dotnet/runtime/issues/25555
- Open Issues for .NET Standard
  * https://github.com/dotnet/standard/issues/1474
  * https://github.com/dotnet/standard/issues/1769
