### ISSUE TITLE
Optional Modbus transactions

### ISSUE THREAD

**Issue by taai** [AndreasAmMueller/Modbus#18]
I have a device ZHC1921 that apparently does not support Modbus transactions, so I get the ```Received response for NOT REQUESTED transaction #0.``` messages in the logs. It would be great if there was a way to turn the transactions off.

**Comment by AndreasAmMueller** [comment]
As the transaction ID is the identifying sequence to find the correct TaskCompletionSource, I think that would cause a malicious behaviour on the client.

I mean... I can provide a flag to disable the transaction ID check, but you might become a wrong answer to your request as the received response cannot be assigned properly to the request.    
If that is fine for you, you'll get what you're asking for, but I strongly recommend to contact the manufacturer of the server side implementation to fix that non-spec behaviour.

**Comment by AndreasAmMueller** [comment]
`DisableTransactionId = true` implemented in v1.2.0
