### ISSUE TITLE
Provide a Task to await the client connection

### ISSUE THREAD

**Issue by ygoe** [AndreasAmMueller/Modbus#2]
As the ModbusClient constructor takes a host name and port and then asynchronously connects to the Modbus server, the consumer of that instance does not know when the client will actually be connected. Polling the IsConnected property is the only option for now.

I suggest adding a Task that completes when the connection has been established. This Task can be awaited by the consumer of the object to continue using the Modbus connection. The Task could be provided by a TaskCompletionSource whose result is set when the connection has been established.

This would be similar to the [Asynchronous Initialization Pattern](https://blog.stephencleary.com/2013/01/async-oop-2-constructors.html) described by Stephen Cleary.

For completeness, the Task should be replaced with a new instance when the connection is closed and the client tries to reconnect. (A completed Task cannot switch to an incomplete state anymore.)

**Comment by AndreasAmMueller** [comment]
Implemented in 27b3567.
