### ISSUE TITLE
HandleWriteMultipleRegisters error

### ISSUE THREAD

**Issue by hmarius** [AndreasAmMueller/Modbus#5]
Hello,
I think I found an error in handling write multiple registers as a tcp slave.
Maybe you can take a look at the submited PR
Thank you

**Comment by AndreasAmMueller** [comment]
Good Morning,
I'll check your issue during the weekend and review your changes.

Thank you for your reply!

**Comment by AndreasAmMueller** [comment]
Sorry for the delay... had some other issues at work to solve first.

Your absolutely right. Thank you :-)

Pull-Request is merged. - Close
